name: Convert JSON to SRS

on:
  push:
    branches:
      - main # 在 main 分支推送时触发
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: 一键安装 sing-box
      - name: Install sing-box
        run: |
          bash <(curl -fsSL https://sing-box.app/deb-install.sh)
          sing-box version  # 验证是否安装成功

      # Step 3: 查找并编译 JSON 文件为 SRS 文件
      - name: Convert JSON files to SRS
        run: |
          for file in $(find ./Files/config/sing-box -name '*.json'); do
            # 使用 sing-box 将 JSON 文件编译为 SRS
            output_file="${file%.json}.srs"
            sing-box rule-set compile --output "$output_file" "$file"
            echo "Compiled $file to $output_file"
          done

      # Step 4: 提交生成的 SRS 文件
      - name: Push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add .
          git commit -m "Auto convert JSON files to SRS"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
